### PR TITLE
77 setup testing

### PR DESCRIPTION
**Pull request by remaininlight**
#### Issues this PR relates to
#34 

=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

.env file has moved into server directory
node_modules should be deleted and reinstalled for client and server
Run the tests with the commands in the readme

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. 

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

### CODE REVIEW

**Review by RamyAlshurafa — CHANGES_REQUESTED** [review]
when i run npm run test:client i get this error (i deleted the node modules and installed them as in the description and this error is the same whether i run it from the root or the client with `npm test`)
image

**Comment by thejoefriel** [comment]
Hey @remaininlight I pushed a couple of fixes as I realised there's some confusing stuff around the root package vs server package. I've also done a fix on client which is to do with react-scripts

One thing though when I load is I get this: 
https://www.loom.com/share/2acbf6a8abc845e8ab03fdb9a7b07fd0

Are those messages to do with your PR or on the app generally? If on app then let's merge this and we can raise this as a bug to resolve but if on yours then do you mind looking into it please?

Thanks!

Joe

**Comment by remaininlight** [comment]
Thanks Joe!

> Are those messages to do with your PR or on the app generally?
I'm not sure, I've not seen the develop branch running yet. Hopefully @cemalokten might be able to corroborate please?

**Comment by cemalokten** [comment]
> Thanks Joe!
> 
> > Are those messages to do with your PR or on the app generally?
> 
> I'm not sure, I've not seen the develop branch running yet. Hopefully @cemalokten might be able to corroborate please?

These messages are because the backend logic hasn't been updated to match the modified database schema, Fadi mocked some API calls to make the front page work, these messages/errors will be resolved.

**Pull request merged**
